package org.tekfive.keep.migration

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption

/**
 * A reviewed-before-application PostgreSQL migration plan.
 *
 * Statements do not include trailing semicolons. [toSql] and [writeTo] render a complete SQL
 * script. Files are not overwritten unless explicitly requested.
 */
data class PostgresMigrationPlan(
    val statements: List<String>,
    val suppressedStatements: List<SuppressedPostgresMigrationStatement> = emptyList(),
) {
    val isEmpty: Boolean
        get() = statements.isEmpty() && suppressedStatements.isEmpty()

    fun toSql(): String = buildString {
        appendLine("-- Generated by KEEP's PostgreSQL migration generator.")
        if (suppressedStatements.isNotEmpty()) {
            appendLine("-- ${suppressedStatements.size} destructive statement(s) were suppressed.")
        }
        if (statements.isNotEmpty()) {
            appendLine()
            append(statements.joinToString(";\n\n", postfix = ";\n"))
        }
    }

    fun writeTo(path: Path, overwrite: Boolean = false): Path {
        path.toAbsolutePath().parent?.let(Files::createDirectories)
        val options = if (overwrite) {
            arrayOf(StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE)
        } else {
            arrayOf(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)
        }
        Files.writeString(path, toSql(), *options)
        return path
    }
}
