package org.tekfive.keep.schema

import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption

/** Complete PostgreSQL SQL for installing a [KeepSchema] into an empty database. */
data class PostgresFreshInstallPlan(
    val statements: List<String>,
) {
    val isEmpty: Boolean
        get() = statements.isEmpty()

    fun toSql(): String = buildString {
        appendLine("-- Generated by KEEP's PostgreSQL fresh-install generator.")
        if (statements.isNotEmpty()) {
            appendLine()
            append(statements.joinToString(";\n\n", postfix = ";\n"))
        }
    }

    fun writeTo(path: Path, overwrite: Boolean = false): Path {
        path.toAbsolutePath().parent?.let(Files::createDirectories)
        val options = if (overwrite) {
            arrayOf(StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE)
        } else {
            arrayOf(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)
        }
        Files.writeString(path, toSql(), *options)
        return path
    }
}
