package org.tekfive.keep.migration.dynamic

import org.jetbrains.exposed.v1.jdbc.Database
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption

/** Ordered operations produced by schema comparison or assembled explicitly. */
data class PostgresMigrationPlan(
    val statements: List<PostgresMigrationStatement>,
    val suppressedStatements: List<SuppressedPostgresMigrationStatement> = emptyList(),
) {
    val isEmpty: Boolean get() = statements.isEmpty() && suppressedStatements.isEmpty()
    val sqlStatements: List<String> get() = statements.map { it.toSql() }

    fun toSql(): String = buildString {
        appendLine("-- Generated by KEEP's PostgreSQL migration generator.")
        if (suppressedStatements.isNotEmpty()) appendLine("-- ${suppressedStatements.size} destructive statement(s) were suppressed.")
        if (statements.any { it.transactionRequirement == TransactionRequirement.AUTOCOMMIT }) {
            appendLine("-- Contains operations requiring autocommit; do not wrap this script in a transaction.")
        }
        if (statements.isNotEmpty()) {
            appendLine()
            append(sqlStatements.joinToString(";\n\n", postfix = ";\n"))
        }
    }

    fun writeTo(path: Path, overwrite: Boolean = false): Path {
        path.toAbsolutePath().parent?.let(Files::createDirectories)
        val options = if (overwrite) arrayOf(StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE)
        else arrayOf(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)
        Files.writeString(path, toSql(), *options)
        return path
    }

    /** Executes atomically, joining an existing transaction on this database when present. */
    fun execute(database: Database): Int = PostgresMigrationExecutor.execute(this, database)

    /** Executes inside the caller's Exposed transaction, without committing it. */
    fun execute(): Int = PostgresMigrationExecutor.execute(this)

    /** Explicit non-atomic execution on a dedicated connection. Successful earlier statements persist on failure. */
    fun executeAutocommit(database: Database): Int = PostgresMigrationExecutor.executeAutocommit(this, database)
}

data class SuppressedPostgresMigrationStatement(
    val statement: PostgresMigrationStatement,
    val reason: DestructivePostgresMigrationChange,
) {
    val sql: String get() = statement.toSql()
}
